name: audio_player
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  flutter_animate: ^4.2.0+1
  animate_gradient: ^0.0.2+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  chopper: ^6.1.4
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  infinite_carousel: ^1.0.3
  # collection: ^1.17.1
  path_provider: ^2.0.15
  sqlite3_flutter_libs: ^0.5.0
  sqflite: ^2.3.0
  drift: ^2.10.0
  path: ^1.8.3
  get_it: ^7.6.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  audioplayers: ^5.1.0
  just_audio: ^0.9.34
  settings_ui: ^2.0.2
  modal_bottom_sheet: ^3.0.0-pre
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  permission_handler: ^10.4.5
  image_picker: ^1.0.4
  # flutter_image_compress: ^2.0.4
  google_sign_in: ^6.1.5
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_picker: ^2.1.0
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.2
  image: ^4.0.17
  firebase_storage: ^11.2.6
  file_picker: ^5.5.0
  # image_picker_for_web: ^3.0.1
  # share_plus: ^7.1.0
  volume_controller: ^2.0.7
  mocktail: ^1.0.0
  http: ^1.1.0
  nock: ^1.2.2
  golden_toolkit: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  build_runner: ^2.4.6
  chopper_generator: ^6.0.3
  drift_dev: ^2.10.0

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/images/

  fonts:  
    - family: CormorantInfant
      fonts:
        - asset: assets/fonts/CormorantInfant-Regular.ttf
    - family: Lusitana
      fonts:
        - asset: assets/fonts/Lusitana-Regular.ttf    
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf  

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#191818"
  # background_image: "assets/unicon_background.png"
  image: "assets/images/sound.png"
  android_12:
    image: "assets/images/sound_1152.png"
   # icon_background_color: "#ffffff"
    color: "#191818"